//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgEntregasAlvaroChema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class pedidos : INotifyPropertyChanged, ICloneable
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private void notificarPropertyChanged([CallerMemberName] string propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public object Clone()
        {
            return this.MemberwiseClone();
        }

        //public int id_pedido { get; set; }
        private int _id_pedido;

        public int id_pedido
        {
            get { return _id_pedido; }
            set { _id_pedido = value;
                notificarPropertyChanged();
            }
        }

        //public string cliente { get; set; }
        private string _cliente;

        public string cliente
        {
            get { return _cliente; }
            set { _cliente = value; notificarPropertyChanged(); }
        }

        //public System.DateTime fecha_pedido { get; set; }
        private System.DateTime _fecha_pedido;

        public System.DateTime fecha_pedido
        {
            get { return _fecha_pedido; }
            set { _fecha_pedido = value; notificarPropertyChanged(); }
        }

        //public string descripcion { get; set; }
        private string _descripcion;

        public string descripcion
        {
            get { return _descripcion; }
            set { _descripcion = value; notificarPropertyChanged(); }
        }

        //public Nullable<System.DateTime> fecha_entrega { get; set; }
        private Nullable<System.DateTime> _fecha_entrega;

        public Nullable<System.DateTime> fecha_entrega
        {
            get { return _fecha_entrega; }
            set { _fecha_entrega = value; notificarPropertyChanged(); }
        }

        //public byte[] firma { get; set; }
        private byte[] _firma;

        public byte[] firma
        {
            get { return _firma; }
            set { _firma = value; notificarPropertyChanged(); }
        }


        //public virtual clientes clientes { get; set; }
        private clientes _clientes;

        public virtual clientes clientes
        {
            get { return _clientes; }
            set { _clientes = value; notificarPropertyChanged(); }
        }
    }
}