//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgEntregasAlvaroChema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class provincias : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provincias()
        {
            this.clientes = new HashSet<clientes>();
        }
    
        //public int id_provincia { get; set; }
        private int _id_provincia;

        public int id_provincia
        {
            get { return _id_provincia; }
            set { _id_provincia = value;
                notificarPropertyChanged();
            }
        }

        //public string nombre_provincia { get; set; }
        private string _nombre_provincia;

        public event PropertyChangedEventHandler PropertyChanged;
        private void notificarPropertyChanged([CallerMemberName] string propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public string nombre_provincia
        {
            get { return _nombre_provincia; }
            set { _nombre_provincia = value;
                notificarPropertyChanged();
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<clientes> clientes { get; set; }
        private ICollection<clientes> _clientes;

        public virtual ICollection<clientes> clientes
        {
            get { return _clientes; }
            set { _clientes = value;
                notificarPropertyChanged();
            }
        }

    }
}
